name: Deploy To Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dodoyuuu/ssh-scp-ssh-pipelines@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.ACCT_USER }}
          pass: ${{ secrets.ACCT_PASS }}
          scp: |
            './*' => ${{ secrets.SERVER_PATH }}